repos:
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: 628f6aeaeb488ae497b918ceda9cc2b0eaa02079
  hooks:
  - id: pretty-format-kotlin
    args: [--autofix, --ktlint-version 11.6.1]
